"use client";

import "./globals.css";

import { ThemeProvider, CssBaseline, useMediaQuery, createTheme } from "@mui/material";
import { useMemo } from "react";

export default function RootLayout({ children }: { children: React.ReactNode }) {
	const prefersDarkMode = useMediaQuery('(prefers-color-scheme: dark)');

	const theme = useMemo(
		() =>
			createTheme({
				palette: {
					mode: prefersDarkMode ? 'dark' : 'light',
				},
			}),
		[prefersDarkMode],
	);

	return (
		<html lang="en">
			<head>
				<title>Create Next App</title>
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<ThemeProvider theme={theme}>
				<body id="__next">
					<CssBaseline />
					{children}
				</body>
			</ThemeProvider>
		</html>
	);
}
